name: Jacob's Website Deployment

on:
  repository_dispatch:
    types: [build]
  push:
    branches:
    - master

env:
  BUCKET_NAME : ${{ secrets.AWS_BUCKET }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  AWS_REGION : "us-east-1"

# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.IAM_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to S3
      env:
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        folder: docs
      run: |
        cd $folder
        aws s3 sync . s3://$aws_bucket/